version: '3.8'

services:
  musetalk:
    build:
      context: .
      dockerfile: Docker.cuda.yml
    ports:
      - "7866:7866"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./:/app/
